version: "3.7"

services:
  node-red:
    build: ./node-red
    ports:
      - "1880:1880"
    volumes:
      - node-red-data:/data

  sinatra:
    build: ./sinatra
    ports:
#      - 4567:4567
      - 80:4567
volumes:
  node-red-data:

