version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    volumes:
      - node-red-data:/data

  sinatra:
    build: ./sinatra
    ports:
      - 4567:4567

volumes:
  node-red-data:

